### ISSUE TITLE
sort and per/page button CSS broken on IE11 (or if JS is disabled)

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2251] opened 2020-03-02 20:35 UTC
Via Slack last week, @mejackreed suggested that Blacklight is expected to work on IE11 (since Bootstrap supports IE 10-11), and problems would be welcome as GH issues. 

This is a screenshot of a Blacklight 7.6.0 app created with Blacklight quickstart, using Rails 5.2.4.1.  I don't beleive the Rails versions is relevant; I just had trouble creating a quickstart Blacklight app on latest rails 6, per #2250; I believe the repro of this one would be identical on rails 6 however. 

![Screenshot 2020-03-02 15 31 37](https://user-images.githubusercontent.com/149304/75715191-031add80-5c9b-11ea-8d3d-6f52b4672eca.png)

Accessed via browserstack.com, a Windows 10/IE11 session. 

Accessing current https://demo.projectblacklight.org on IE11 exhibits similar problem. 

I don't believe this is new to Blacklight 7.6.0 -- I believe it may be as old as possibly Blacklight 7.4.2, maybe older. Because my own current custom app also exhibits the problem. But I reproduced on a fresh new quickstart app as well as demo.projectblacklight.org for a cleaner error report on the newest Blacklight version.

**Comment by jrochkind** [comment] 2020-03-04 16:02
Aha, it turns out this is what happens when JS is not loaded. So it's actually caused by #2252 , fixing that would make this appear fixed. 

UNLESS you want it to display correct in a user-agent with Javascript disabled. This is basically what it looks like if Javascript is disabled (you can disable JS in your browser of choice to see) -- or if JS fails to load due to syntax error as on IE in #2252

**Comment by mejackreed** [comment] 2020-03-04 16:13
I think this is how it should look if JS is disabled, so perhaps I would suggest closing this issue. Sort and per page dropdowns are kind of out of luck for better aesthetics without JavaScript.

**Closed** 2021-11-09 21:34 UTC
Labels: design-needed

**Comment by jcoyne** [comment] 2021-11-09 21:41
Duplicate of #2252
