### ISSUE TITLE
Add built-in support for preventing deep paging

### ISSUE THREAD

**Issue by tampakis** [projectblacklight/blacklight#2178] opened 2019-10-09 21:09 UTC
Deep paging can cause Solr to crash. Out of the box ~Solr~ Blacklight should remove the pagination options at the bottom of the page to click to the last pages of the results.

Several institutions also block deep paging in their apps. Add a config option to set the max page limit.

**Comment by cdmo** [comment] 2019-10-18 12:53
Let's include banning deep paging in facets too with this issue. Ok?

**Comment by cdmo** [comment] 2019-10-18 12:56
You know, I think this is a duplicate of #1665, so I'm going to close. Please reopen if I'm wrong.

**Closed by cdmo** 2019-10-18 12:56 UTC
