### ISSUE TITLE
'production' environment not working on fresh install

### ISSUE THREAD

**Issue by roelpaesen** [projectblacklight/blacklight#1924] opened 2018-07-10 15:15 UTC
Hi,
when I follow the quickstart-procedure (easy or hard makes no difference), I can at the end run 'rails server', but when I try to switch to the production-environment ('rails server -e production') I get errors...
ruby 2.5
rails 5.2.0
blacklight install as on 2018-07-10 (17h13 GMT+2)

Error codes:

```
rpaesen@u1804:~/projects/search_app$ rails server -e production
=> Booting Puma
=> Rails 5.2.0 application starting in production
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
        95: from bin/rails:3:in `<main>'
        94: from bin/rails:3:in `load'
        93: from /home/rpaesen/projects/search_app/bin/spring:15:in `<top (required)>'
        92: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        91: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        90: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `                                                              <top (required)>'
        89: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `                                                              load'
        88: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (requi                                                              red)>'
        87: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `r                                                              un'
        86: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:                                                              7:in `call'
        85: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28                                                              :in `call'
        84: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28                                                              :in `load'
        83: from /home/rpaesen/projects/search_app/bin/rails:9:in `<top (required)>'
        82: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:29:in `require'
        81: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        80: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/loaded_features_index.rb:65:in `register'
        79: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        78: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `require'
        77: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in                                                               `<main>'
        76: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in                                                               `invoke'
        75: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:6                                                              5:in `perform'
        74: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        73: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in                                                               `invoke_command'
        72: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run                                                              '
        71: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/s                                                              erver_command.rb:142:in `perform'
        70: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/s                                                              erver_command.rb:142:in `tap'
        69: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/s                                                              erver_command.rb:147:in `block in perform'
        68: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/s                                                              erver_command.rb:53:in `start'
        67: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:283:in `star                                                              t'
        66: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrap                                                              ped_app'
        65: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/s                                                              erver_command.rb:27:in `app'
        64: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
        63: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `buil                                                              d_app_and_options_from_config'
        62: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `pars                                                              e_file'
        61: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_                                                              from_string'
        60: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval                                                              '
        59: from config.ru:in `<main>'
        58: from config.ru:in `new'
        57: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `init                                                              ialize'
        56: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `inst                                                              ance_eval'
        55: from config.ru:3:in `block in <main>'
        54: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:44:in `require_relative'
        53: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:29:in `require'
        52: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        51: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/loaded_features_index.rb:65:in `register'
        50: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        49: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `require'
        48: from /home/rpaesen/projects/search_app/config/environment.rb:5:in `<main>'
        47: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:36                                                              1:in `initialize!'
        46: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:                                                              60:in `run_initializers'
        45: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        44: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        43: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        42: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
        41: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
        40: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_co                                                              mponent'
        39: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_f                                                              rom'
        38: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_c                                                              onnected_component'
        37: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        36: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:                                                              61:in `block in run_initializers'
        35: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:                                                              32:in `run'
        34: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:                                                              32:in `instance_exec'
        33: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application/finis                                                              her.rb:69:in `block in <module:Finisher>'
        32: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application/finis                                                              her.rb:69:in `each'
        31: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:356:in                                                               `eager_load!'
        30: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:475:in                                                               `eager_load!'
        29: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:475:in                                                               `each'
        28: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:477:in                                                               `block in eager_load!'
        27: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:477:in                                                               `each'
        26: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:478:in                                                               `block (2 levels) in eager_load!'
        25: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/active_support.rb:59:in `depend_on'
        24: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dep                                                              endencies/interlock.rb:13:in `loading'
        23: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/con                                                              currency/share_lock.rb:151:in `exclusive'
        22: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dep                                                              endencies/interlock.rb:14:in `block in loading'
        21: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:29:in `require'
        20: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        19: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/loaded_features_index.rb:65:in `register'
        18: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        17: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `require'
        16: from /home/rpaesen/projects/search_app/app/models/marc_indexer.rb:2:in `<main>'
        15: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:29:in `require'
        14: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        13: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/loaded_features_index.rb:65:in `register'
        12: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        11: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `require'
        10: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-marc-6.2.0/lib/blacklight/marc/                                                              indexer.rb:2:in `<main>'
         9: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:29:in `require'
         8: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         7: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/loaded_features_index.rb:65:in `register'
         6: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
         5: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/kernel_require.rb:21:in `require'
         4: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/null_writer.rb:3                                                              :in `<main>'
         3: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/active_support.rb:42:in `load_missing_constant'
         2: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
         1: from /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cach                                                              e/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active                                                              _support.rb:53:in `block in load_missing_constant': uninitialized constant Traject (NameError)
```

**Comment by jcoyne** [comment] 2018-07-10 15:41
The cause here is that `Traject` is referenced, but you've never required the `traject` gem.

**Comment by roelpaesen** [comment] 2018-07-12 09:50
I tried 'gem install traject', but that gives no change... (same error appears)

**Comment by jcoyne** [comment] 2018-07-12 12:30
Installed on your machine is not the same as "required" which means loaded into the program.

**Comment by jcoyne** [comment] 2018-07-12 12:31
Where is your code? I'd have a look at `app/models/marc_indexer.rb`

**Comment by roelpaesen** [comment] 2018-07-12 12:32
The code is on this github, it is a non-altered install following the easy-quick-install as described here.
Only difference is that I tried to run 'rails server -e production' instead of 'rails server'

**Comment by jcoyne** [comment] 2018-07-12 12:43
@roelpaesen I'm sorry, I don't see a link to the repository you're mentioning. Can you post it here?

**Comment by roelpaesen** [comment] 2018-07-12 12:45
[https://github.com/projectblacklight/blacklight](https://github.com/projectblacklight/blacklight)
and from there, follow this guide: https://github.com/projectblacklight/blacklight/wiki/Quickstart
just, at the end, run 'rails server -e production' instead of 'rails server'

**Comment by roelpaesen** [comment] 2018-07-12 13:11
So, next problem :)
The server starts fine, however opening the any page gives an error (see below)
It seems that favicon,ico is missing, however this file is present in /app/assets/favicon.ico (blank file, created it myself, world has read-premissions)

Any idea where this file should be if not in /app/assets?


I, [2018-07-12T13:06:43.437088 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1] Started GET "/" for 192.168.56.1 at 2018-07-12 13:06:43 +0000
I, [2018-07-12T13:06:43.447757 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1] Processing by CatalogController#index as HTML
D, [2018-07-12T13:06:43.476082 #2854] DEBUG -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1] Solr query: get select {"qt"=>nil, "facet.field"=>["format", "{!ex=pub_date_single}pub_date", "subject_topic_facet", "language_facet", "lc_1letter_facet", "subject_geo_facet", "subject_era_facet"], "facet.query"=>["pub_date:[2013 TO *]", "pub_date:[2008 TO *]", "pub_date:[1993 TO *]"], "facet.pivot"=>["format,language_facet"], "fq"=>[], "hl.fl"=>[], "rows"=>10, "facet"=>true, "f.subject_topic_facet.facet.limit"=>21, "f.language_facet.facet.limit"=>11, "sort"=>"score desc, pub_date_sort desc, title_sort asc"}
D, [2018-07-12T13:06:43.476178 #2854] DEBUG -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1] Solr fetch (16.3ms)
I, [2018-07-12T13:06:43.479655 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   Rendering /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-6.15.0/app/views/catalog/index.html.erb within layouts/blacklight
I, [2018-07-12T13:06:43.484040 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   Rendered /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-6.15.0/app/views/catalog/_facets.html.erb (0.7ms)
I, [2018-07-12T13:06:43.484158 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   Rendered /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-6.15.0/app/views/catalog/_search_sidebar.html.erb (2.1ms)
I, [2018-07-12T13:06:43.489895 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   Rendered /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-6.15.0/app/views/catalog/_home_text.html.erb (3.5ms)
I, [2018-07-12T13:06:43.489955 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   Rendered /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-6.15.0/app/views/catalog/_home.html.erb (4.8ms)
I, [2018-07-12T13:06:43.491331 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   Rendered /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-6.15.0/app/views/shared/_sitelinks_search_box.html.erb (0.3ms)
I, [2018-07-12T13:06:43.491384 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   Rendered /home/rpaesen/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-6.15.0/app/views/catalog/index.html.erb within layouts/blacklight (11.6ms)
I, [2018-07-12T13:06:43.493151 #2854]  INFO -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1] Completed 500 Internal Server Error in 45ms
F, [2018-07-12T13:06:43.494055 #2854] FATAL -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   
F, [2018-07-12T13:06:43.494087 #2854] FATAL -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1] ActionView::Template::Error (The asset "favicon.ico" is not present in the asset pipeline.):
F, [2018-07-12T13:06:43.494224 #2854] FATAL -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]     18: 
[614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]     19:     <title><%= render_page_title %></title>
[614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]     20:     <%= opensearch_description_tag application_name, opensearch_catalog_url(:format => 'xml') %>
[614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]     21:     <%= favicon_link_tag %>
[614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]     22:     <%= stylesheet_link_tag "application", media: "all" %>
[614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]     23:     <%= javascript_include_tag "application" %>
[614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]     24:     <%= csrf_meta_tags %>
F, [2018-07-12T13:06:43.494246 #2854] FATAL -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1]   
F, [2018-07-12T13:06:43.494273 #2854] FATAL -- : [614fa0ee-739f-4fb4-86d6-e0d9e1bd76e1] sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:83:in `compute_asset_path'

etc more info on the render path

**Comment by cdmo** [comment] 2018-08-21 19:47
I just hit this problem on `7rc1` too, deploying code to a server. Had to add `traject` to my `Gemfile`.

I tried:

```rb
    config.enable_dependency_loading = true
    config.autoload_paths << Rails.root.join('lib')
```

in `config/application.rb` because I was hoping it had to do with a change rails made in autoloading.. but perhaps not. Just adding this here in case anyone else runs into this.

**Comment by cdmo** [comment] 2018-08-22 14:51
@roelpaesen you have to the rake task for assets:precompile in order for the ico problem to go away. You may also have to restart the web server.

**Comment by barmintor** [comment] 2018-10-23 21:52
@roelpaesenI am closing this issue as it seems the reported problem - having traject loaded - was solved in your application. Please open a new issue for the subsequent problems if you believe them to be problems with Blacklight!

**Closed by barmintor** 2018-10-23 21:52 UTC
