### ISSUE TITLE
</span> tags showing on facet pagination pages

### ISSUE THREAD

**Issue by peetucket** [projectblacklight/blacklight#2247] opened 2020-02-20 17:53 UTC
On Blacklight v6.22.0.  Expand a facet that with a "more >>" link, see an extra `<span>` or two.  Originally filed under [argo here](https://github.com/sul-dlss/argo/issues/1823) (but the issue shows in searchworks suggesting its coming from blacklight)

**Comment by jcoyne** [comment] 2020-02-20 17:55
@peetucket is this a duplicate of https://github.com/projectblacklight/blacklight/commit/a746fa59b6b138f7d1f10200da635ad60b4f6fd3 ?

**Comment by peetucket** [comment] 2020-02-20 17:56
certainly looks like it

**Closed** 2020-02-20 17:56 UTC

**Comment by peetucket** [comment] 2020-02-20 18:01
so assuming that fixes it, we need a new release of blacklight (e.g. 6.22.1) so that argo and searchworks will pick it up at the next dependency cycle?  it looks like even though this fix was ported to the 6.x branch, a new release of blacklight wasn't cut ... or is that something that happens on a regular schedule?
