### ISSUE TITLE
Unable to close modal windows 

### ISSUE THREAD

**Issue by tampakis** [projectblacklight/blacklight#1798] opened 2017-10-12 17:24 UTC
If a user requests a new page within a modal (ie paginates through the facet values, or submits the email/SMS form) the modal window doesn't close when clicking the "x" at the top right corner. This is only an issue in the master branch.

**Comment by jcoyne** [comment] 2017-10-29 18:46
Duplicate of #1641 (fixed)

**Closed by jcoyne** 2017-10-29 18:46 UTC
