### ISSUE TITLE
Quickstart still broken

### ISSUE THREAD

**Issue by markamccann** [projectblacklight/blacklight#1591] opened 2016-12-01 16:48 UTC
I'm investigating Blacklight and have no Ruby/Rails dev background.   In case anybody cares, as of Dec 1, your Quickstart guide is still broken.  I have tried the following:

Clean install of everything on OSX following "Easy and Hard" instructions.  Result: many failures.
Clean install of everything on a new Ubuntu 16 VM installed with Vagrant following "Easy" instructions:  Result: failure.

Here is the final error message for the Ubuntu Easy install attempt:
"The template [https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb] could not be loaded. Error: cannot load such file -- solr_wrapper"

This is probably something simple to fix for an experience Ruby/Rails dev.  Looking at the template.demo.rb script, I see the "require solr_wrapper" line and my guess is that that resource isn't being found for some reason or another.

I might decide to spend a few days learning Ruby/Rails to see if I can figure it out myself, but it would be nice to have something basic that works for people new to Blacklight.

**Comment by cbeer** [comment] 2016-12-01 16:52
Can you include the complete output from using the application template? Our intent and expectation is that it will work, but without more information I'm not sure we can assist.

**Comment by markamccann** [comment] 2016-12-01 17:02
Thanks for the reply Chris.  Complete output below.  Just to recap, this is what I did just now:
1) brand new Ubuntu 16 64-bit install using Vagrant
2) Installed ruby 2.3.1 and rails 5.0.0.1
3) Installed OpenJDK 8

All of the above is per the "Quickstart" instructions.
Next I ran the commands below following the "Create a new application the easy way" from the  Quickstart guide:

vagrant@vagrant:~/projects$ javac -version
javac 1.8.0_111
vagrant@vagrant:~/projects$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
vagrant@vagrant:~/projects$ rails -v
Rails 5.0.0.1

vagrant@vagrant:~$ mkdir projects 
vagrant@vagrant:~$ cd projects/
vagrant@vagrant:~/projects$ rails new search_app -m https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb
      create  
      create  README.md
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
      remove  config/initializers/cors.rb
       apply  https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb
     gemfile    blacklight (>= 6.1)
         run    bundle install from "."
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 11.3.0
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Installing minitest 5.10.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Installing execjs 2.7.0
Installing sass 3.4.22
Using bundler 1.13.6
Using method_source 0.8.2
Using thor 0.19.4
Installing byebug 9.0.6 with native extensions
Installing coffee-script-source 1.11.1
Installing debug_inspector 0.0.2 with native extensions
Installing ffi 1.9.14 with native extensions
Installing multi_json 1.12.1
Installing rb-fsevent 0.9.8
Installing puma 3.6.2 with native extensions
Installing tilt 2.0.5
Installing sqlite3 1.3.12 with native extensions
Installing turbolinks-source 5.0.0
Using tzinfo 1.2.2
Installing rsolr 1.1.2
Using nokogiri 1.6.8.1
Using rack-test 0.6.3
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Installing autoprefixer-rails 6.5.3
Installing uglifier 3.0.4
Installing coffee-script 2.4.1
Installing rb-inotify 0.9.7
Installing turbolinks 5.0.1
Using activesupport 5.0.0.1
Using loofah 2.0.3
Using mail 2.6.4
Installing bootstrap-sass 3.3.7
Installing listen 3.0.8
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Installing deprecation 1.0.0
Installing jbuilder 2.6.1
Installing spring 2.0.0
Using rails-html-sanitizer 1.0.3
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Installing spring-watcher-listen 2.0.1
Using actionview 5.0.0.1
Using actionpack 5.0.0.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Installing kaminari 0.17.0
Using railties 5.0.0.1
Using sprockets-rails 3.2.0
Installing jquery-rails 4.2.1
Installing coffee-rails 4.2.1
Installing web-console 3.4.0
Using rails 5.0.0.1
Installing sass-rails 5.0.6
Installing twitter-typeahead-rails 0.11.1.pre.corejavascript
Installing blacklight 6.7.2
Bundle complete! 16 Gemfile dependencies, 69 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
    generate    blacklight:install
Expected string default value for '--jbuilder'; got true (boolean)
    generate  blacklight:solr5
Expected string default value for '--jbuilder'; got true (boolean)
     gemfile  group :development, :test
      append  Gemfile
     gemfile  solr_wrapper (>= 0.3)
      append  Gemfile
      append  Rakefile
      create  solr
      create  solr/conf/_rest_managed.json
      create  solr/conf/admin-extra.html
      create  solr/conf/elevate.xml
      create  solr/conf/mapping-ISOLatin1Accent.txt
      create  solr/conf/protwords.txt
      create  solr/conf/schema.xml
      create  solr/conf/scripts.conf
      create  solr/conf/solrconfig.xml
      create  solr/conf/spellings.txt
      create  solr/conf/stopwords.txt
      create  solr/conf/stopwords_en.txt
      create  solr/conf/synonyms.txt
      create  solr/conf/xslt/example.xsl
      create  solr/conf/xslt/example_atom.xsl
      create  solr/conf/xslt/example_rss.xsl
      create  solr/conf/xslt/luke.xsl
      create  solr/sample_solr_documents.yml
      create  .solr_wrapper.yml
     gemfile  rsolr (~> 1.0)
         run  bundle install from "."
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.3.0
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.10.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using execjs 2.7.0
Using sass 3.4.22
Using bundler 1.13.6
Using method_source 0.8.2
Using thor 0.19.4
Using byebug 9.0.6
Using coffee-script-source 1.11.1
Using debug_inspector 0.0.2
Installing multipart-post 2.0.0
Using ffi 1.9.14
Using multi_json 1.12.1
Using rb-fsevent 0.9.8
Using puma 3.6.2
Installing ruby-progressbar 1.8.1
Installing rubyzip 1.2.0
Using tilt 2.0.5
Using sqlite3 1.3.12
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using rsolr 1.1.2
Using nokogiri 1.6.8.1
Using rack-test 0.6.3
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Using autoprefixer-rails 6.5.3
Using uglifier 3.0.4
Using coffee-script 2.4.1
Installing faraday 0.10.0
Using rb-inotify 0.9.7
Using turbolinks 5.0.1
Using activesupport 5.0.0.1
Using loofah 2.0.3
Using mail 2.6.4
Using bootstrap-sass 3.3.7
Installing solr_wrapper 0.19.0
Using listen 3.0.8
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Using deprecation 1.0.0
Using jbuilder 2.6.1
Using spring 2.0.0
Using rails-html-sanitizer 1.0.3
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Using spring-watcher-listen 2.0.1
Using actionview 5.0.0.1
Using actionpack 5.0.0.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Using kaminari 0.17.0
Using railties 5.0.0.1
Using sprockets-rails 3.2.0
Using jquery-rails 4.2.1
Using coffee-rails 4.2.1
Using web-console 3.4.0
Using rails 5.0.0.1
Using sass-rails 5.0.6
Using twitter-typeahead-rails 0.11.1.pre.corejavascript
Using blacklight 6.7.2
Bundle complete! 18 Gemfile dependencies, 74 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
    generate  blacklight:assets
Expected string default value for '--jbuilder'; got true (boolean)
      create  app/assets/stylesheets/blacklight.scss
      insert  app/assets/javascripts/application.js
    generate  blacklight:document
Expected string default value for '--jbuilder'; got true (boolean)
      create  app/models/solr_document.rb
    generate  blacklight:search_builder
Expected string default value for '--jbuilder'; got true (boolean)
      create  app/models/search_builder.rb
    generate  blacklight:models
Expected string default value for '--jbuilder'; got true (boolean)
      create  config/blacklight.yml
        rake  blacklight:install:migrations
Copied migration 20161201163608_create_searches.blacklight.rb from blacklight
Copied migration 20161201163609_create_bookmarks.blacklight.rb from blacklight
Copied migration 20161201163610_add_polymorphic_type_to_bookmarks.blacklight.rb from blacklight
       route  
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
    generate  blacklight:user
Expected string default value for '--jbuilder'; got true (boolean)
     gemfile  devise
     gemfile  devise-guests (~> 0.5)
         run  bundle install from "."
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.3.0
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.10.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using execjs 2.7.0
Installing bcrypt 3.1.11 with native extensions
Using sass 3.4.22
Using bundler 1.13.6
Using method_source 0.8.2
Using thor 0.19.4
Using byebug 9.0.6
Using coffee-script-source 1.11.1
Using debug_inspector 0.0.2
Installing orm_adapter 0.5.0
Using multipart-post 2.0.0
Using ffi 1.9.14
Using multi_json 1.12.1
Using rb-fsevent 0.9.8
Using puma 3.6.2
Using ruby-progressbar 1.8.1
Using rubyzip 1.2.0
Using tilt 2.0.5
Using sqlite3 1.3.12
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using rsolr 1.1.2
Using nokogiri 1.6.8.1
Using rack-test 0.6.3
Using sprockets 3.7.0
Installing warden 1.2.6
Using websocket-driver 0.6.4
Using mime-types 3.1
Using autoprefixer-rails 6.5.3
Using uglifier 3.0.4
Using coffee-script 2.4.1
Using faraday 0.10.0
Using rb-inotify 0.9.7
Using turbolinks 5.0.1
Using activesupport 5.0.0.1
Using loofah 2.0.3
Using mail 2.6.4
Using bootstrap-sass 3.3.7
Using solr_wrapper 0.19.0
Using listen 3.0.8
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Using deprecation 1.0.0
Using jbuilder 2.6.1
Using spring 2.0.0
Using rails-html-sanitizer 1.0.3
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Using spring-watcher-listen 2.0.1
Using actionview 5.0.0.1
Using actionpack 5.0.0.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Using kaminari 0.17.0
Using railties 5.0.0.1
Using sprockets-rails 3.2.0
Using jquery-rails 4.2.1
Using coffee-rails 4.2.1
Installing responders 2.3.0
Using web-console 3.4.0
Using rails 5.0.0.1
Using sass-rails 5.0.6
Using twitter-typeahead-rails 0.11.1.pre.corejavascript
Installing devise 4.2.0
Using blacklight 6.7.2
Installing devise-guests 0.5.0
Bundle complete! 20 Gemfile dependencies, 80 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
    generate  devise:install
Expected string default value for '--jbuilder'; got true (boolean)
      create  config/initializers/devise.rb
      create  config/locales/devise.en.yml
===============================================================================

Some setup you must do manually if you haven't yet:

  1. Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  4. You can copy Devise views (for customization) to your app by running:

       rails g devise:views

===============================================================================
    generate  devise
Expected string default value for '--jbuilder'; got true (boolean)
      invoke  active_record
      create    db/migrate/20161201163620_devise_create_users.rb
      create    app/models/user.rb
      invoke    test_unit
      create      test/models/user_test.rb
      create      test/fixtures/users.yml
      insert    app/models/user.rb
       route  devise_for :users
    generate  devise_guests
Expected string default value for '--jbuilder'; got true (boolean)
      invoke  active_record
      create    db/migrate/20161201163621_add_devise_guests_to_users.rb
      insert  app/models/user.rb
        gsub  config/initializers/devise.rb
      insert  app/models/user.rb
    generate  blacklight:controller
Expected string default value for '--jbuilder'; got true (boolean)
      insert  app/controllers/application_controller.rb
      create  app/controllers/catalog_controller.rb
       route    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end
       route  root to: "catalog#index"
      insert  config/application.rb
      create  config/locales/blacklight.en.yml
     gemfile  blacklight-marc (~> 6.1)
         run  bundle install from "."
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 11.3.0
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.10.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using execjs 2.7.0
Using bcrypt 3.1.11
Using sass 3.4.22
Using bundler 1.13.6
Using method_source 0.8.2
Using thor 0.19.4
Installing library_stdnums 1.4.1
Installing scrub_rb 1.0.1
Installing unf_ext 0.0.7.2 with native extensions
Installing dot-properties 0.1.3
Installing hashie 3.4.6
Installing httpclient 2.8.2.4
Installing slop 3.6.0
Installing yell 2.0.7
Using byebug 9.0.6
Using coffee-script-source 1.11.1
Using debug_inspector 0.0.2
Using orm_adapter 0.5.0
Using multipart-post 2.0.0
Using ffi 1.9.14
Using multi_json 1.12.1
Using rb-fsevent 0.9.8
Using puma 3.6.2
Using ruby-progressbar 1.8.1
Using rubyzip 1.2.0
Using tilt 2.0.5
Using sqlite3 1.3.12
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using rsolr 1.1.2
Using nokogiri 1.6.8.1
Using rack-test 0.6.3
Using sprockets 3.7.0
Using warden 1.2.6
Using websocket-driver 0.6.4
Using mime-types 3.1
Using autoprefixer-rails 6.5.3
Using uglifier 3.0.4
Installing unf 0.1.4
Using coffee-script 2.4.1
Using faraday 0.10.0
Using rb-inotify 0.9.7
Using turbolinks 5.0.1
Using activesupport 5.0.0.1
Using loofah 2.0.3
Using mail 2.6.4
Using bootstrap-sass 3.3.7
Installing marc 1.0.0
Using solr_wrapper 0.19.0
Using listen 3.0.8
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Using deprecation 1.0.0
Using jbuilder 2.6.1
Using spring 2.0.0
Using rails-html-sanitizer 1.0.3
Installing marc-fastxmlwriter 1.0.0
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Using spring-watcher-listen 2.0.1
Using actionview 5.0.0.1
Installing traject 2.3.2
Using actionpack 5.0.0.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Using kaminari 0.17.0
Using railties 5.0.0.1
Using sprockets-rails 3.2.0
Using jquery-rails 4.2.1
Using coffee-rails 4.2.1
Using responders 2.3.0
Using web-console 3.4.0
Using rails 5.0.0.1
Using sass-rails 5.0.6
Using twitter-typeahead-rails 0.11.1.pre.corejavascript
Using devise 4.2.0
Using blacklight 6.7.2
Using devise-guests 0.5.0
Installing blacklight-marc 6.1.1
Bundle complete! 21 Gemfile dependencies, 93 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
    generate  blacklight:marc:install
Expected string default value for '--jbuilder'; got true (boolean)
      insert  app/assets/stylesheets/blacklight.scss
      create  config/translation_maps
      create  config/translation_maps/README_MAPS
      create  config/translation_maps/callnumber_map.properties
      create  config/translation_maps/composition_era_map.properties
      create  config/translation_maps/country_map.properties
      create  config/translation_maps/format_map.properties
      create  config/translation_maps/instrument_map.properties
      create  config/translation_maps/language_map.properties
      create  app/models/marc_indexer.rb
      insert  app/models/solr_document.rb
      insert  app/controllers/catalog_controller.rb
       route  Blacklight::Marc.add_routes(self)
       route  mount Blacklight::Engine => '/'
        rake    db:migrate
== 20161201163608 CreateSearches: migrating ===================================
-- create_table(:searches, {})
   -> 0.0019s
== 20161201163608 CreateSearches: migrated (0.0023s) ==========================

== 20161201163609 CreateBookmarks: migrating ==================================
-- create_table(:bookmarks, {})
   -> 0.0018s
== 20161201163609 CreateBookmarks: migrated (0.0023s) =========================

== 20161201163610 AddPolymorphicTypeToBookmarks: migrating ====================
== 20161201163610 AddPolymorphicTypeToBookmarks: migrated (0.0063s) ===========

== 20161201163620 DeviseCreateUsers: migrating ================================
-- create_table(:users)
   -> 0.0011s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0011s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0007s
== 20161201163620 DeviseCreateUsers: migrated (0.0042s) =======================

== 20161201163621 AddDeviseGuestsToUsers: migrating ===========================
-- change_table(:users, {})
   -> 0.0009s
== 20161201163621 AddDeviseGuestsToUsers: migrated (0.0013s) ==================

The template [https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb] could not be loaded. Error: cannot load such file -- solr_wrapper

**Comment by atz** [comment] 2016-12-01 22:49
duplicate of #1393 ?

**Comment by markamccann** [comment] 2016-12-01 23:35
Yes, I say those issues.  However, given that they were from Feb and apparently nobody addressed them, I thought there was a chance somebody would notice a new issue.  Chris did.  BTW, I did manage to get a bit further.  Without a doubt, there are a number of problems with the current Quickstart guide.  The biggest problem is the reference to "--jetty-wapper" rather than solr.  It is clear to me that nobody none of the Blacklight contributors have actually gone through the Quickstart guide for real with a clean install.  Probably trivial issues to fix, so would be great if somebody would do this.  This is the first impression anybody new to Blacklight will get after all!  Cheers,
Mark

**Comment by atz** [comment] 2016-12-02 02:14
Just linked the other ticket here for cross-reference, and to see if you identify the issue as related or unrelated.  Thanks for reporting this.  You are correct that there is mounting maintenance debt.

**Comment by atz** [comment] 2016-12-02 02:16
See also #1069, #1379, #1459

**Comment by markamccann** [comment] 2016-12-02 16:52
Might I suggest that if this isn't going to be fixed by somebody today (just take 10 minutes to follow my steps above and I think you'll see the problem), you might want to put a big warning at the top of the quickstart guide to say that the instructions below are currently broken?  The "How to get started" button is the most prominent thing on the main project page http://projectblacklight.org/ and anybody who actually "tries to get started" will get the impression this project is neglected or possibly in threat of being abandoned.

**Comment by anarchivist** [comment] 2016-12-02 18:42
Hi @markamccann, we're really sorry that you're running into this issue, and we absolutely agree that we need to address the Quickstart issue to make sure that the problem you've run into is addressed and doesn't happen for others. To start, we've edited the Quickstart instructions to add a workaround for the first issue, and to recommend installing `solr_wrapper` first as a prerequisite. You may still run into some additional issues (such as #1379), but are working to address those as well. 

@cbeer and I both have verified your issue, but have limited time to work on it at the moment beyond what we've done so far. Those of us who have done our best to help you also have other responsibilities at work and maintain Blacklight as an additional (and often external) responsibility, so a speedy turn around on this might be a challenge. Please also remember that we also have multiple support channels, our [mailing list](http://groups.google.com/group/blacklight-development) (a Google Group) is the best way to get multiple eyes on an issue from folks in the Blacklight community who aren't necessarily committers or maintainers.

**Comment by markamccann** [comment] 2016-12-02 22:53
Hi @anarchivist, thanks for the response.  As busy full-stack dev myself (no Ruby/Rails experience or I'm sure I could fix this myself), I completely understand that there are often aspects of projects that fall through the cracks (ie install guides, documentation, etc).  As you suggest, the change to "solr_wrapper" fixed the first issue, but then things go off the rails again at step 2 of "Easy or Hard: After creating your new application".  I'll be happy to do a full clean run through of the Quickstart guide again when somebody has time to fix it completely (I understand this could be weeks or months since we are all busy people).

**Comment by anarchivist** [comment] 2016-12-03 07:05
It looks like we've been able to resolve these issues. Please try another run through and let us know if you get blocked.

**Comment by markamccann** [comment] 2016-12-05 21:39
Hi @anarchivist, looks like your Quickstart fixes worked.  I was able to follow the "Hard way" instructions to get Solr and Rails up and index the sample Marc data.    One last fly in the ointment: I tried to index some real Marc data (some .mrc binary data exported from our catalog) and I immediately ran into a bug that I think is addressed by this pull request: https://github.com/projectblacklight/blacklight-marc/pull/37
So, it works for the sample data, but I'm not sure if works on any real .mrc data?  I guess we could almost close this one.

**Comment by markamccann** [comment] 2016-12-05 22:05
Ok, so the pull request for the blacklight-marc gem mentioned above does indeed work.  If somebody updates the quickstart guide to mention the step of applying this patch before injesting any real-world-marc binary, I think the Quickstart is working perfectly again.   Any idea way https://github.com/projectblacklight/blacklight-marc/pull/37 has been open for so long?

**Comment by hackmastera** [comment] 2017-11-17 16:40
looks like this can be closed. @cbeer?

**Comment by barmintor** [comment] 2018-10-23 22:51
Closing since the relevant blacklight-marc patch was released in v6.2.0 of that gem. Tracking v7.0.0 quickstart issues in other tickets.

**Closed by barmintor** 2018-10-23 22:51 UTC
